name: fitness_app_ii_example
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # line chart
  fl_chart: ^0.66.2

  youtube_player_flutter: ^9.0.0

  get: ^4.6.6

  google_fonts: ^6.2.0

  sqflite: ^2.3.2

  path_provider: ^2.1.2
  intl: ^0.19.0

  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
#    - assets/videos/