name: fitness_app_ii_example
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # line chart
  fl_chart: ^0.12.1

  # video
  video_player: ^1.0.1

  get: ^3.26.0

  google_fonts: ^1.1.2

  sqflite: ^1.3.2+4

  path_provider: ^1.6.28

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/